In [ ]:
import numpy as np
from scipy.stats import multivariate_normal
import torch
import pandas as pd

In [ ]:
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [ ]:
def generate_mesh_and_z(sigma1, sigma2, sigma3):
    """
    Generates a mesh grid and corresponding probability density values for a mixture
    of three 2D Gaussian distributions.

    Args:
    sigma1 (torch.Tensor): The covariance tensor for the first Gaussian distribution.
    sigma2 (torch.Tensor): The covariance tensor for the second Gaussian distribution.
    sigma3 (torch.Tensor): The covariance tensor for the third Gaussian distribution.

    Returns:
    tuple: Tuple containing mesh grid arrays (xx, yy) and the corresponding probability
    density values (zz).
    """
    N_points = 10
    xl = -2
    xr = 2

    x = np.linspace(xl, xr, N_points+1)
    xx, yy = np.meshgrid(x, x)

    X = torch.tensor(np.column_stack([xx.ravel(), yy.ravel()]), dtype=torch.float32)

    mu1 = torch.tensor([1, 1], dtype=torch.float32)
    mu2 = torch.tensor([1, -1], dtype=torch.float32)
    mu3 = torch.tensor([-1, -1], dtype=torch.float32)

    z1 = torch.tensor(multivariate_normal.pdf(X.numpy(), mu1.numpy(), sigma1.numpy()), dtype=torch.float32)
    z2 = torch.tensor(multivariate_normal.pdf(X.numpy(), mu2.numpy(), sigma2.numpy()), dtype=torch.float32)
    z3 = torch.tensor(multivariate_normal.pdf(X.numpy(), mu3.numpy(), sigma3.numpy()), dtype=torch.float32)

    zz = (z1 + z2 + z3).reshape(xx.shape)

    return xx, yy, zz

In [ ]:
sigma1_d = 0.15 * torch.eye(2)
sigma2_d = 0.2 * torch.eye(2)
sigma3_d = 0.3 *torch.eye(2)

In [ ]:
xx, yy, zz = generate_mesh_and_z(sigma1_d, sigma2_d, sigma3_d)

In [ ]:
fig = go.Figure(data=[go.Surface(z=zz.numpy(), x=xx, y=yy)])
fig.update_layout(scene=dict(aspectmode='data'))
fig.update_layout(scene=dict(camera=dict(eye=dict(x=2, y=2, z=1))))

#fig.show()

In [ ]:
X = torch.tensor(np.column_stack([xx.ravel(), yy.ravel()]), dtype=torch.float32)

In [ ]:
T = 4
x_norm = ( X - X.min() ) / ( ( X.max() - X.min() ) / T )

In [ ]:
x_norm

tensor([[0.0000, 0.0000],
        [0.4000, 0.0000],
        [0.8000, 0.0000],
        [1.2000, 0.0000],
        [1.6000, 0.0000],
        [2.0000, 0.0000],
        [2.4000, 0.0000],
        [2.8000, 0.0000],
        [3.2000, 0.0000],
        [3.6000, 0.0000],
        [4.0000, 0.0000],
        [0.0000, 0.4000],
        [0.4000, 0.4000],
        [0.8000, 0.4000],
        [1.2000, 0.4000],
        [1.6000, 0.4000],
        [2.0000, 0.4000],
        [2.4000, 0.4000],
        [2.8000, 0.4000],
        [3.2000, 0.4000],
        [3.6000, 0.4000],
        [4.0000, 0.4000],
        [0.0000, 0.8000],
        [0.4000, 0.8000],
        [0.8000, 0.8000],
        [1.2000, 0.8000],
        [1.6000, 0.8000],
        [2.0000, 0.8000],
        [2.4000, 0.8000],
        [2.8000, 0.8000],
        [3.2000, 0.8000],
        [3.6000, 0.8000],
        [4.0000, 0.8000],
        [0.0000, 1.2000],
        [0.4000, 1.2000],
        [0.8000, 1.2000],
        [1.2000, 1.2000],
        [1.6000, 1.2000],
        [2.0

In [ ]:
t  = x_norm.numpy().astype(int)

In [ ]:
x_n = x_norm - t


In [ ]:

class SubBlock:
    def __init__(self, vertices):
        self.vertices = vertices
        self.points_inside = []

    def is_point_inside(self, point):
        x, y = point[0], point[1]
        x0, y0 = self.vertices[0][0], self.vertices[0][1]
        x1, y1 = self.vertices[2][0], self.vertices[2][1]
        return (x0 <= x < x1) and (y0 <= y < y1)

    def add_point(self, point):
        if self.is_point_inside(point):
            ("aaaaaaaaaaaaa")
            self.points_inside.append(point)



def get_sub_block_vertices(grid_size, row, col):
    delta = 1.0 / grid_size
    x0 = col * delta
    x1 = (col + 1) * delta
    y0 = row * delta
    y1 = (row + 1) * delta
    return np.array([[x0, y0], [x1, y0], [x0, y1], [x1, y1]])


def locate_points_in_sub_blocks(x_n, grid_size):
    sub_blocks = np.empty((grid_size, grid_size), dtype=object)

    for row in range(grid_size):
        for col in range(grid_size):
            sub_blocks[row, col] = SubBlock(get_sub_block_vertices(grid_size, row, col))

    for i in range(x_n.shape[0]):
        point = x_n[i]
        for row in range(grid_size):
            for col in range(grid_size):
                sub_block = sub_blocks[row, col]
                print(f" \nverticessss: \n {sub_block.vertices}")
                print(f"poinnnnnt: {point.T}")
                if sub_block.is_point_inside(point):
                    sub_block.add_point(point)
                    break

    return sub_blocks



sub_blocks = locate_points_in_sub_blocks(x_n.numpy(), T)



Se truncaron las últimas líneas 5000 del resultado de transmisión.
 [0.5  0.5 ]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.5  0.25]
 [0.75 0.25]
 [0.5  0.5 ]
 [0.75 0.5 ]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.75 0.25]
 [1.   0.25]
 [0.75 0.5 ]
 [1.   0.5 ]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.   0.5 ]
 [0.25 0.5 ]
 [0.   0.75]
 [0.25 0.75]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.25 0.5 ]
 [0.5  0.5 ]
 [0.25 0.75]
 [0.5  0.75]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.5  0.5 ]
 [0.75 0.5 ]
 [0.5  0.75]
 [0.75 0.75]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.75 0.5 ]
 [1.   0.5 ]
 [0.75 0.75]
 [1.   0.75]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.   0.75]
 [0.25 0.75]
 [0.   1.  ]
 [0.25 1.  ]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.25 0.75]
 [0.5  0.75]
 [0.25 1.  ]
 [0.5  1.  ]]
poinnnnnt: [0.        0.4000001]
 
verticessss: 
 [[0.5  0.75]
 [0.75 0.75]
 [0.5  1.  ]
 [0.75

In [ ]:

for row in sub_blocks:
  for block in row:
    print(f'Block vertices: {block.vertices}')
    print(f'Block points inside: {block.points_inside}')

In [ ]:
for row in sub_blocks:
  for block in row:
    print(f'Block vertices: {block.vertices[2]}')